name: Compress Images

on:
  push:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install imagemin-cli
        run: npm install -g imagemin-cli

      - name: Compress Images
        run: imagemin '**/*.{jpg,jpeg,png,webp}' --out-dir=compressed/

      - name: Commit compressed images
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add compressed/
          git commit -m "Compress images"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
